### ISSUE TITLE
ReferenceError: fs is not defined 

### ISSUE THREAD

**Issue by tnatarajan** [mhevery/jasmine-node#186]
In the latest version of jasmine-node, we are getting **ReferenceError: fs is not defined** error in cli.js.

`usr/local/lib/node_modules/jasmine-node/lib/jasmine-node/cli.js:89`
`var existsSync = fs.existsSync || path.existsSync;`

  This was introduced by the [commit](https://github.com/mhevery/jasmine-node/commit/80e436274187cdfbdca7b1a9ce7078c917105d41#lib/jasmine-node/cli.js) made on Dec 05, 2012. 

Hope the following initialization  should be included in the cli.js
`var fs = require('fs');`

**Comment by smallWanziOf** [comment]
me too . when use 'less-vars-to-js' who know this ? thanks!!!
