### ISSUE TITLE
failing test not showing in jasmine-node when using the --coffee switch

### ISSUE THREAD

**Issue by opensas** [mhevery/jasmine-node#211]
I have the following basic test for a web service:

```
var request = require('http'),
    url     = 'http://localhost:1337/';

describe('webservice', function() {

  it('should respond to /ping', function(done) {
    request.get(url + 'ping', function(res) {
      expect(res.statusCode).toBe(200);
      res.on('data', function(body) {
        var json = JSON.parse(body);
        expect(json.message).toBe("Hi, I'm alive");
        expect(json.date).toBeDefined();
        done();
      });
    });

  });

});
```

which seems to work ok:

```
$ jasmine-node --verbose tests/ping/

webservice
    should respond to /ping

Finished in 0.032 seconds
1 test, 3 assertions, 0 failures
```

But if I make one test fail (change the expected json message, for example) I get the following error:

```
$ jasmine-node --verbose --coffee tests/ping/
StreamWrap: Aborting due to unwrap failure at ../src/stream_wrap.cc:125
Aborted (core dumped)
```

Any idea what could I be doing wrong?

(more over, any mistake I have in my js, the test just silently fails, with no clue on waht happened, the js errors just dissapears)

update: the error appears only if the failing test is inside the request.get callback...

ps: also askes at SO in case anybody wants to earn a couple of reputation points: http://stackoverflow.com/questions/15469980/failing-test-not-showing-in-jasmine-node
ps2: I couldn't find a google group for this project...

**Comment by christophetd** [comment]
I'm getting the same issue years later with Node v5.10.1.
