### ISSUE TITLE
Documentation: missing info re setting async timeouts

### ISSUE THREAD

**Issue by dg-colin** [mhevery/jasmine-node#232]
The README mentions setting jasmine.DEFAULT_TIMEOUT_INTERVAL, but omits crucial information about how to do this. A colleague of mine. through debugging, figured out we could set it globally before running a suite (i.e. a describe() block) via

```
jasmine.getEnv().defaultTimeoutInterval = myPreferredTimeoutInMillisecs;
```

Before we did this, every other place we tried setting  jasmine.DEFAULT_TIMEOUT_INTERVAL it simply got over-ridden or reset.

Being able to set this is vital for Webdriver-driven UI tests which often need more than 5 seconds to complete.

**Comment by DirtyMoney** [comment]
Same for me, I added it to the jasmine-runner.js like you can see below.
The tests still fail if they take longer than 5 seconds.

```javascript 
var Jasmine = require('jasmine');
var SpecReporter = require('jasmine-spec-reporter');
var noop = function() {};

var jrunner = new Jasmine();
jrunner.configureDefaultReporter({print: noop});
jasmine.getEnv().addReporter(new SpecReporter({
	displayStacktrace: 'none',
	displayFailuresSummary: true,
	displayPendingSummary: true,
	displaySuccessfulSpec: true,
	displayFailedSpec: true,
	displayPendingSpec: true,
	displaySpecDuration: true,
	displaySuiteNumber: false,
	colors: {
		success: 'green',
		failure: 'red',
		pending: 'yellow'
	},
	prefixes: {
		success: 'V ',
		failure: 'X ',
		pending: '* '
	},
	customProcessors: []
}));
jasmine.getEnv().defaultTimeoutInterval = 15000;
jrunner.loadConfigFile();
jrunner.execute();
