### ISSUE TITLE
Errors thrown by asynchronous code crash jasmine-node

### ISSUE THREAD

**Issue by jwoudenberg** [mhevery/jasmine-node#267]
I've stumbled upon what I think is a bug in jasmine-node while testing code containing Q based promises. I've written a testcase in this gist:

https://gist.github.com/jwoudenberg/6906155

When running this test from the console, I see one dot for the first completed test and then it just stops. No error, no test-summary, nothing.

Running the same test with the stand-alone jasmine package seems to work fine and reports that the second (and third) errors have failed.

So what's going on here?

**Comment by Giszmo** [comment]
**`--captureExceptions`** totally does the trick. I wonder why that is not the default :( Would have saved me many many hours.
