### ISSUE TITLE
Mock Clock's clearTimeout/clearInterval don't work

### ISSUE THREAD

**Issue by bonnici** [mhevery/jasmine-node#276]
When using jasmine.Clock.useMock(), the setTimeout and setInterval functions use the proper mocked versions, but clearTimeout/clearInterval use the default system functions, so the fake timeouts are not cleared. I noticed one typo in the code:

```
jasmine.getGlobal().clearInterval = function(timeoutKey) {
  if (jasmine.Clock.installed.clearTimeout.apply) {
```

should be 

```
jasmine.getGlobal().clearInterval = function(timeoutKey) {
  if (jasmine.Clock.installed.clearInterval.apply) {
```

But that didn't fix the problem and I couldn't work out why it wasn't working. Tested using this code:

```
it("should clear timeouts", function() {
    jasmine.Clock.useMock();
    var timeoutId = setTimeout(function() { expect(true).toEqual(false); }, 10);
    clearTimeout(timeoutId);
    jasmine.Clock.tick(20);
});
it("should clear intervals", function() {
    jasmine.Clock.useMock();
    var intervalId = setInterval(function() { expect(true).toEqual(false); }, 10);
    clearInterval(intervalId);
    jasmine.Clock.tick(20);
});
```

**Comment by LegalizeAdulthood** [comment]
Thanks for this, it fixed my problem!

**Comment by datrinh** [comment]
How would this look like with the latest API?`I'm struggling with the same problem currently.
