### ISSUE TITLE
Webstorm debug?

### ISSUE THREAD

**Issue by Agamennon** [mhevery/jasmine-node#299]
how do i debug a spec? can i use webstorm to do it? how?

thanks!

**Comment by jperry** [comment]
@Agamennon - can you elaborate more as to what you did to be able to debug tests using jasmine-node from webstorm?

**Comment by 4kochi** [comment]
This is our configuration in Webstorm. Works fine.

![bildschirmfoto 2015-02-11 um 10 00 29](https://cloud.githubusercontent.com/assets/1742426/6144218/f7fb2ea8-b1d4-11e4-867a-179b7cc022e1.png)

We use grunt-jasmine-node and therefore grab the jasmine-node file from there.

**Comment by jperry** [comment]
thanks @4kochi . that worked for me!  Do you have a way of running one test at a time?

**Comment by 4kochi** [comment]
In Jasmine itself you can use iit() instead of it() to run just that test. The same works with describe(). But i don't know if jasmine-node supports that. Maybe @tebriel can give us a hint.
