### ISSUE TITLE
Jasmine-node --version displaying the wrong version number (jasmine-node@1.14.5)

### ISSUE THREAD

**Issue by RandomLetter** [mhevery/jasmine-node#350]
Installed jasmine-node@1.14.5 via npm (with -g flag).
ran 'jasmine-node --version' --> get 1.14.3
checked lib/cli.js under 1.14.5 tagged branch and printVersion is hardcoded to print '1.14.3'

As a result I'm not sure if I have 1.14.5 or 1.14.3 installed.  Checking earlier tagged branches it looks like cli.js printVersion() command was being updated to match the version number of the branch.

Thanks!

**Comment by christopherbalz** [comment]
I get the same issue.

**Comment by kevindperezm** [comment]
Same here
