### ISSUE TITLE
Question: how to run tests across multiple files?

### ISSUE THREAD

**Issue by mchavarriagam** [mhevery/jasmine-node#360]
Guys,

I'm sorry for asking what is probably a very silly question but I haven't been able to figure this out, haven't found anything in the documentation explaining how to do it (only stating that it is supported), and even by looking at the code I couldn't find what I am looking for.

I have several _spec.js files that I need to run to feed their results into Istanbul code coverage. If I run them individually the coverage report won't be accurate, and I don't want to merge what are A LOT of tests into a single file (very ugly). So far I've tried doing:

```
jasmine-node tests/integration/*_spec.js
jasmine-node --match tests/integration/*_spec.js
jasmine-node --matchall tests/integration/
jasmine-node --test-dir <absolute path>
jasmine-node <file1>_spec.js <file2>_spec.js <file3>_spec.js
```

with no luck.

What am I missing? Documentation states:

```
Ability to specify multiple files to test via list in command line
```

And

```
Individual files to test can be added as bare arguments to the end of the args.
Example:
jasmine-node --coffee spec/AsyncSpec.coffee spec/CoffeeSpec.coffee spec/SampleSpec.js
```

I'm using jasmine-node v 1.14.5 btw.

Thanks!

**Comment by Luchillo** [comment]
You can close it yourself.

**Comment by mchavarriagam** [comment]
Oops, thanks!
