### ISSUE TITLE
How can I add a custom matcher?

### ISSUE THREAD

**Issue by Janekk** [mhevery/jasmine-node#365]
Following the [documentation of original Jasmine](http://jasmine.github.io/2.0/custom_matcher.html) there should be a method `jasmine.addMatchers(customMatchers);` but it's not available in jasmine-node. How can I add a custom matcher then?

**Comment by Janekk** [comment]
Oh, searched around a little bit and apparently there is another syntax for specyfying matchers, using this.addMatchers and different object structures (an example [here](http://joelhooks.com/blog/2012/11/17/using-custom-jasmine-matchers-to-make-unit-tests-more-readable/)). 

Closed.

**Comment by jedwards1211** [comment]
I assume the jasmine env in jasmine-node should be the same as what pure jasmine provides though?
