### ISSUE TITLE
possible bug with .and.call...

### ISSUE THREAD

**Issue by 9Dave9** [mhevery/jasmine-node#376]
http://stackoverflow.com/questions/30560195/how-to-spy-on-a-class-method-in-node-jasmine/30561820#30561820

Essentially when I run the tests using the global `NODE_ENV=test jasmine-node --captureExceptions --verbose tests_to_run_spec.js`  I get 

```bash
  1) Auddth #AuthStrategies.localStrategy when user creds are valid returns user object
   Message:
     TypeError: Cannot call method 'callFake' of undefined
   Stacktrace:
     TypeError: Cannot call method 'callFake' of undefined
    at null.<anonymous> (/home/davidp/workspace/sharescore/spec/jasmine/src/server/lib/auth_spec.js:22:43)

  2) Auddth #AuthStrategies.localStrategy when user creds are valid returns user object
   Message:
     timeout: timed out after 5000 msec waiting for spec to complete
   Stacktrace:
     undefined
```

But when I run 

`NODE_ENV=test ./node_modules/.bin/jasmine-node --captureExceptions ./spec/jasmine/src/server/lib/auth_spec.js` 

 all is absolutely fine .. just like all my other tests. 

I am lost. it's weird behaviour and I have broken this down into the smallest of components.  I tried requiring modules where I was already using the callThrough and callFake on in other tests. But got the same errors when doing it in this file. The thing is - behaviour changes when I call jasmine-node using the fully specified name - hence me thinking this may actually be a bug as opposed to my n00bishness.

Any thoughts?

**Comment by 9Dave9** [comment]
oh wow - 

If I run 

'NODE_ENV=test jasmine-node --captureExceptions ./spec/jasmine' in the terminal I get the bad behaviour(every callFake and callThrough) breaks. 

But if I run the exact same thing as a node task. it's all fine. i.e -  `npm run test`  - all my tests pass.

**Comment by shoebox639** [comment]
@9Dave9 Are you using Jasmine2.0? If not, the `.and.callFake` syntax only exists in Jasmine 2 and your errors are real. I'm not sure why `npm run test` works. Maybe it's just ignoring all the syntax errors and not actually running any tests.

**Comment by 9Dave9** [comment]
@shoebox639 - it was in fact jasmine 2.0(Jasmine-node seems to be wrapped on this version unfortunately). Anyways - some how I was having a random issue on my system and unfortunately now can't reproduce this bug, Thank you very much for getting back me.  I'll close this now.
