### ISSUE TITLE
Question: how to run tests across multiple files? (redux)

### ISSUE THREAD

**Issue by fergiemcdowall** [mhevery/jasmine-node#377]
I have been using Jasmine-node for a while over at  https://github.com/fergiemcdowall/search-index

This is my test command in [package.json](https://github.com/fergiemcdowall/search-index/blob/master/package.json):
`rm -rf si* backup.gz && NODE_ENV=test jasmine-node --verbose test/spec/0indexing-spec.js && jasmine-node --verbose test/spec/0.1indexing-spec.js && jasmine-node --verbose test/spec/1.0searching-spec.js && jasmine-node --verbose test/spec/1.5get-doc-spec.js && jasmine-node --verbose test/spec/2deleting-spec.js && jasmine-node --verbose test/spec/2.1deleting-spec.js && jasmine-node --verbose test/spec/4faceting-spec.js && jasmine-node --verbose test/spec/3matching-spec.js && jasmine-node --verbose test/spec/4.5range-facet-spec.js && jasmine-node --verbose test/spec/5replication-spec.js && jasmine-node --verbose test/spec/6config-spec.js && jasmine-node --verbose test/spec/7indexing-without-ids-spec.js && jasmine-node --verbose test/spec/8indexing-numbers-spec.js && jasmine-node --verbose test/spec/9filter-spec.js && jasmine-node --verbose test/spec/9.1range-filter-spec.js && jasmine-node --verbose test/spec/9.6instantiation-spec.js && jasmine-node --verbose test/spec/9.7nonasciichar-spec.js"`

...which is obviously far too long and really vulnerable to files being forgotten or left out. However, `jasmine-node` doesnt seem to let me specify *-spec.js, it just fails silently. 

So my question is- how do you specify and run multiple test files? Is there a way to break multiple test files into groups? Can they be run in order (synchronously)? How _should_ I be using `jasmine-node` to test `search-index`?

(Apologies if there is a good write up about this somewhere, but Intense googling over many hours has left me none the wiser)

**Comment by diogommartins** [comment]
jasmine-node lets you specify a pattern. At `PACKAGE_ROOT_DIR/spec/support/jasmine.json`, you can use an expression at `spec_files`

``` javascript 
{
  "spec_dir": "spec",
  "spec_files": [
    "**/*[sS]pec.js"
  ],
  "helpers": [
    "helpers/**/*.js"
  ],
  "stopSpecOnExpectationFailure": false,
  "random": false
}
```
With that expression, everything under `PACKAGE_ROOT_DIR/spec/` which ends with `spec.js` or `Spec.js` will run when you run `jasmine-node spec`. 
Wich leaves you with a shorter version of your test script: `"test": "jasmine-node --verbose spec"`

**Comment by fergiemcdowall** [comment]
@diogommartins thanks for the tip. Closing..
