### ISSUE TITLE
Can't run jasmine-node with node 4 using ES6a

### ISSUE THREAD

**Issue by indigo0086** [mhevery/jasmine-node#386]
Running jasmine-node using node 4 against a spec file that uses es6 generates the following error in the presence of any es6 specific syntax.

```
[SyntaxError: Unexpected reserved word]
```

**Comment by noahzgordon** [comment]
+1

**Comment by jan-osch** [comment]
+1

**Comment by suhasdeshpande** [comment]
Is there any resolution on this one??

**Comment by diogommartins** [comment]
jasmine-node doesn't work with ES6 syntax. you have to use something like babel to compile it. My testing routine for my npm `package.json` is 
``` javascript
"scripts": {
    "pretest": "babel src --out-dir lib && babel spec/*.es6 --out-dir .",
    "test": "./node_modules/.bin/jasmine-node --verbose --captureExceptions spec",
    "compile": "babel src --out-dir lib",
    "prepublish": "npm test && npm run compile",
    "doc": "esdoc -c ./esdoc.json"
  },
```

**Comment by erajune** [comment]
@diogommartins Which babel did you install?

**Comment by diogommartins** [comment]
@erajune I'm currently using 
```
"devDependencies": {
    "babel-cli": "^6.0.0",
    "babel-polyfill": "^6.8.0",
    "babel-preset-es2015": "^6.6.0",
    "jasmine-node": "^1.14.5"
}
```

**Comment by brodybits** [comment]
This looks like the request is for something beyond the scope of this project. Marked as a feature request that will be declined, especially considering this project is now in maintenance mode.
