### ISSUE TITLE
Upgrade gaze version

### ISSUE THREAD

**Issue by AryanJ-NYC** [mhevery/jasmine-node#411]
`jasmine-node` uses `gaze 0.3.2`.  This version of gaze uses a version of `minimatch` that may cause a [RegExp DoS issue](https://github.com/npm/npm/issues/13323).

Please upgrade to avoid issues.

**Comment by mbaluda** [comment]
Please update to gaze 1.1.0 
https://github.com/shama/gaze/issues/220

**Comment by brodybits** [comment]
Fixed by #427, which was recently merged.
