### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by nenadg** [mhevery/jasmine-node#412]
Hi all, 

what's the status of this project? 

There haven't been any commits/merges since 2014 so I wonder is this still live project or you guy gave up on it?

**Comment by Shyam-Chen** [comment]
Mocha & Chai

**Comment by vitaly-t** [comment]
Looking at the log of issues, it is clear this project has been abandoned.

**Comment by VzqzAc** [comment]
Jasmine BDD itself offers good node.js support now in my opinion

**Comment by Shyam-Chen** [comment]
https://github.com/jasmine/jasmine-npm

**Comment by brodybits** [comment]
I was added as a collaborator to take over maintenance for packages that really need it. I just documented the project status to be "maintenance mode". It is recommended to use `jasmine` or `jasmine-npm` package whenever possible. Closing now.
