### ISSUE TITLE
jasmine-node process never finishes

### ISSUE THREAD

**Issue by blindsey** [mhevery/jasmine-node#71]
I'm seeing some weirdness with jasmine-node 1.0.7 and node 0.4.11. My process never finishes. Who is supposed to send the 'exit' signal?

**Comment by natarajanmca11** [comment]
in Istanbul Code coverage `--forceexit` is not working for me. anyone can help in this case ?

`e:\api>istanbul cover --include-all-source
s ./node_modules/jasmine-node/bin/jasmine-node ./dist/ --forceexit`

**Comment by metacoding** [comment]
@natarajanmca11 I also had the same issue `jasmine-node ./src --autotest --verbose --forceexit --color`
removing the --autotest flag solved my problem
